apiVersion: v1
kind: ConfigMap
metadata:
  name: cnf-vl3-config
data:
  config.yaml: |
    endpoints:
    - name: {{ .Values.nsm.serviceName | quote }}
      labels:
        app: vl3-nse
      cnns:
        name: {{ .Values.nsm.serviceName | quote }}
        address: "{{ .Values.cnns.addr }}:{{ .Values.cnns.port }}"
    connectivityDomain: {{ .Values.cnns.cd | quote}}
      vl3:
       ipam:
          defaultPrefixPool: {{ .Values.ipam.prefixPool | quote }}
          prefixLength: {{ .Values.ipam.prefixLength | quote }}
          routes: []
       ifName: "endpoint0"
