---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: cnns-nse-vl3-service
spec:
  payload: IP
  matches:
    - match:
      route:
        - destination:
          destinationSelector:
            app: cnns-nse-vl3
