# Default values for mysql-master.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: docker.io
org: tiswanso
tag: unified_api_ipam
pullPolicy: Always

cnns:
  addr: localhost
  port: 5005
  cd: vl3-service-connectivity-domain
    # addr: 
#  domain: nsr.foo.com

nsm:
  serviceName: vl3-service

ipam:
  prefixPool: "172.31.0.0/16"
  # uniqueOctet: 

replicaCount: 1